apiVersion: v1
kind: Service
metadata:
  name: node-redis-riseoblue
  labels:
    app: node-redis-riseoblue
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-redis-riseoblue